---
apiVersion: v1
kind: LimitRange
metadata:
  name: limits
  namespace: dev
spec:
  limits:
    - default:
        cpu: 500m
        memory: 750Mi
      defaultRequest:
        cpu: 100m
        memory: 350Mi
      min:
        cpu: 20m
        memory: 50Mi
      max:
        cpu: 1
        memory: 4Gi
      type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: limits
  namespace: test
spec:
  limits:
    - default:
        cpu: 500m
        memory: 750Mi
      defaultRequest:
        cpu: 100m
        memory: 350Mi
      min:
        cpu: 20m
        memory: 50Mi
      max:
        cpu: 1
        memory: 4Gi
      type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: limits
  namespace: production
spec:
  limits:
    - default:
        cpu: 1
        memory: 2048Mi
      defaultRequest:
        cpu: 500m
        memory: 750Mi
      min:
        cpu: 100m
        memory: 512Mi
      max:
        cpu: 2
        memory: 8Gi
      type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: limits
  namespace: infra
spec:
  limits:
    - default:
        cpu: 1
        memory: 4Gi
      defaultRequest:
        cpu: 500m
        memory: 1Gi
      min:
        cpu: 100m
        memory: 200Mi
      max:
        cpu: 2
        memory: 8Gi
      type: Container
