apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- kube-config/example-co-tls-secret.yml
- kube-config/example-secret.yml
- kube-config/example-deploy.yml
- kube-config/example-svc.yml
- kube-config/example-ingress.yml

namespace: dev

commonLabels:
  app: example
  env: dev