---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
  namespace: dev
spec:
  hard:
    requests.cpu: 10
    requests.memory: 40Gi
    limits.cpu: 20
    limits.memory: 80Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
  namespace: test
spec:
  hard:
    requests.cpu: 10
    requests.memory: 40Gi
    limits.cpu: 20
    limits.memory: 80Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
  namespace: production
spec:
  hard:
    requests.cpu: 20
    requests.memory: 80Gi
    limits.cpu: 40
    limits.memory: 160Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
  namespace: infra
spec:
  hard:
    requests.cpu: 20
    requests.memory: 80Gi
    limits.cpu: 40
    limits.memory: 160Gi
